import { nanoid } from "@reduxjs/toolkit";

export const peopleData = [
  {
    id: nanoid(),
    name: "Marek Szlęk",
    age: 25,
    birthDate: 886892400000,
    resume:
      "Niedawno uzyskałem tytuł magistra Architektury na Politechnice Śląskiej. Podczas studiów odkryłem swoje zainteresowanie programowaniem poprzez architekturę parametryczną (Grasshopper). Od używania Pythona do rozszerzania funkcjonalności programowania graficznego, poprzez naukę Javascriptu z three.js w celu stworzenia aplikacji do symulacji architektonicznych, doszedłem do punktu, w którym chciałbym dalej rozwijać swoje umiejętności programistyczne i kontynuować karierę jako frontend developer. Oto moja aplikacja w Reakcie :)",
  },
  {
    id: nanoid(),
    name: "John Stone",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Mia Wong",
    age: 21,
    birthDate: 601426800000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Peter Stanbridge",
    age: 22,
    birthDate: 926546400000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Ang Li",
    age: 22,
    birthDate: 979513200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Desiree Burch",
    age: 48,
    birthDate: 184719600000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Trevor Virtue",
    age: 53,
    birthDate: 342000000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Eugenia Anders",
    age: 27,
    birthDate: 824943600000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Verona Blair",
    age: 40,
    birthDate: 420501600000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Maureen M. Smith",
    age: 57,
    birthDate: 215996400000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Steve French",
    age: 34,
    birthDate: 601340400000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "Natalie Lee-Walsh",
    age: 41,
    birthDate: 388533600000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
];
