import { nanoid } from "@reduxjs/toolkit";

export const peopleData = [
  {
    id: nanoid(),
    name: "Marek Szlęk",
    age: 25,
    birthDate: 886892400000,
    resume:
      "Niedawno uzyskałem tytuł magistra Architektury na Politechnice Śląskiej. Podczas studiów odkryłem swoje zainteresowanie programowaniem poprzez architekturę parametryczną (Grasshopper). Od używania Pythona do rozszerzania funkcjonalności programowania graficznego, poprzez naukę Javascriptu z three.js w celu stworzenia aplikacji do symulacji architektonicznych, doszedłem do punktu, w którym chciałbym dalej rozwijać swoje umiejętności programistyczne i kontynuować karierę jako frontend developer. Oto moja aplikacja w Reakcie :)",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum nibh id pellentesque efficitur. Phasellus nulla tortor, euismod id auctor id, bibendum nec ligula. Proin a semper urna. Maecenas convallis, nunc in pellentesque eleifend, mauris purus fermentum erat, nec vehicula odio libero vitae elit. Sed ligula sem, vestibulum id ante ac, ullamcorper rutrum enim. Aenean a erat cursus, dignissim tortor non, maximus libero. Fusce non rhoncus ex, sed pellentesque urna.",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
  {
    id: nanoid(),
    name: "John Doe",
    age: 42,
    birthDate: 354409200000,
    resume: "Lorem ipsum",
  },
];
